EjercicioCoches/Controllers/ConductoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EjercicioCoches.Models;

namespace EjercicioCoches.Controllers
{
    public class ConductoresController : Controller
    {

        VehiculosEntities db=new VehiculosEntities();
        // GET: Conductores
        public ActionResult Detalle(int id)
        {
            var c = db.Conductor.Find(id);

            return View(c);
        }

        public ActionResult DetalleAjax(int id)

        {

            db.Configuration.LazyLoadingEnabled = false;
            var c = db.Conductor.Find(id);

            return Json(c,JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            db.Dispose();
        }
    }
}

EjercicioCoches/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EjercicioCoches.Models;

namespace EjercicioCoches.Controllers
{
    public class HomeController : Controller
    {

        VehiculosEntities db=new VehiculosEntities();

        // GET: Home
        public ActionResult Index()
        {
            return View(db.Vehiculo);
        }

        public ActionResult Alta()
        {
            ViewBag.idConductores = 
                new MultiSelectList(db.Conductor, "idConductor", "nombre");


            return View(new Vehiculo());
        }

        [HttpPost]
        public ActionResult Alta(Vehiculo model)
        {
            
            if (ModelState.IsValid)
            {
                db.Vehiculo.Add(model);
                foreach (var idConductor in model.idConductores)
                {
                    var o = db.Conductor.Find(idConductor);
                    model.Conductor.Add(o);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

       
        public ActionResult Modificar(int id)
        {
            var v = db.Vehiculo.Find(id);
            ViewBag.idConductores =
               new MultiSelectList(db.Conductor, "idConductor", "nombre",
                   v.Conductor);


            return View(v);
        }
        [HttpPost]
        public ActionResult Modificar(Vehiculo v)
        {
            if (ModelState.IsValid)
            {
                var va = db.Vehiculo.Find(v.id);
                va.marca = v.marca;
                va.modelo = v.modelo;
                va.matricula = v.matricula;

                va.Conductor.Clear();

                foreach (var idConductor in v.idConductores)
                {
                    var o = db.Conductor.Find(idConductor);
                    va.Conductor.Add(o);
                }

                db.SaveChanges();
                return RedirectToAction("Index");

            }


            return View();
        }
        public ActionResult Borrar(int id)
        {
            var o = db.Vehiculo.Find(id);

            o.Conductor.Clear();
            db.Vehiculo.Remove(o);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult ListadoAjax()
        {
            return  PartialView("_Listado",db.Vehiculo);
        }

        public ActionResult AltaAjax(Vehiculo v)
        {
            db.Vehiculo.Add(v);

            try
            {
                db.SaveChanges();
                return Json("OK");
            }
            catch (Exception e)
            {
                return Json("Error");
            }

            
        }
    }
}

EjercicioCoches/Views/Home/Alta.cshtml
@model EjercicioCoches.Models.Vehiculo

@{
    ViewBag.Title = "Alta";
}

<h2>Alta</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Conductor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("idConductores")
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EjercicioCoches/Views/Home/Index.cshtml
@model IEnumerable<EjercicioCoches.Models.Vehiculo>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@*@Html.ActionLink("Alta","Alta")*@
<a href="#" id="lnkAlta">Nuevo vehículo</a>
<div id="contenido">@Html.Partial("_Listado", Model)</div>


<div id="modAlta" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Nuevo vehículo</h4>
            </div>
            <div class="modal-body">
                <input type="text" id="txtMatricula" placeholder="Matrícula"/>
                <input type="text" id="txtMarca" placeholder="Marca"/>
                <input type="text" id="txtModelo" placeholder="Modelo" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button id="btnGuardar" type="button" class="btn btn-primary">Guardar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="modDetalle" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
               <div id="contenidoDetalle">Soy el detalle</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    
    function detalle(id) {

        $.getJSON("/Conductores/detalleAjax/" + id, function(res) {

            var tx = res.nombre + " " + res.apellidos;
            $("#contenidoDetalle").text(tx);
            $("#modDetalle").modal();

        });


    }

    $(document).ready(function() {

        $("#lnkAlta").click(function() {
            $("#modAlta").modal();
        });

        $("#btnGuardar").click(function() {
            var data = {
                marca: $("#txtMarca").val(),
                modelo: $("#txtModelo").val(),
                matricula: $("#txtMatricula").val()
            };

            $.ajax({
                url: "/Home/AltaAjax",
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                data: JSON.stringify(data),
                success:function(res) {
                    if (res === "OK") {
                        $("#modAlta").modal('hide');
                        $("#contenido").load("/Home/listadoAjax");
                        alert("Alta realizada");
                    } else {
                        
                        alert("Alta no realizada");
                    }

                }


            })

        });

    });


</script>

EjercicioCoches/Views/Home/Modificar.cshtml
@model EjercicioCoches.Models.Vehiculo

@{
    ViewBag.Title = "Modificar";
}

<h2>Modificar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Conductor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("idConductores")

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EjercicioCoches/Views/Home/_Listado.cshtml
@model IEnumerable<EjercicioCoches.Models.Vehiculo>
@foreach (var item in Model)
{
    <div>
        @item.marca
        <br />
        @item.modelo<br />
        @item.matricula

        <ul>
            @foreach (var con in item.Conductor)
            {
                <li>
                    @*@Html.ActionLink(con.nombre + " " + con.apellidos, "Detalle",
                  "Conductores", new { id = con.idConductor }, null)*@

                    <a href="#" onclick="detalle(@con.idConductor)">@con.nombre @con.apellidos</a>

                </li>
            }

        </ul>
        @Html.ActionLink("Modificar", "Modificar", new { item.id })
        @Html.ActionLink("Borrar", "Borrar", new { item.id })
    </div>

}